---

# - name: Determine which replica to fail over to
#   hosts: database_replica
#   vars:
#     pgsqlrep_type_list: [ 'local', 'remote' ]
#   tasks:
#   - name: check for promotion type
#     fail:
#        msg: "promotion_type must be passed as an extra var with 'local' or 'remote'"
#     when: promotion_type is not defined or promotion_type not in pgsqlrep_type_list
#
#   - set_fact:
#       _target: "{{ 'target' if pgsqlrep_type == promotion_type else 'other' }}"
#
#   - name: set up group based on passed parameter
#     group_by:
#       key: promotion_{{_target}}
#
#   - name: show promotion target
#     debug:
#       msg: "{{groups['promotion_'+_target]}}"

- name: Promote secondary HA/DR database to primary
  hosts: database
  become: true
  tasks:
    - name: Get the current PostgreSQL version
      import_role:
        name: samdoran.pgsql-replication
        tasks_from: pgsql_version.yml

    - name: Check recovery.conf
      stat:
        path: /var/lib/pgsql/{{ pgsql_version }}/data/recovery.conf
      register: recovery_conf

    - name: Exit if secondary is already promoted or not in standby mode
      fail:
        msg: Secondary database server is not in standby mode.
      when: recovery_conf.stat.isreg is not defined
      ignore_errors: yes

    - name: Promote secondary PostgreSQL server to primary
      command: /usr/pgsql-{{ pgsql_version }}/bin/pg_ctl promote
      become_user: postgres
      environment:
        PGDATA: /var/lib/pgsql/{{ pgsql_version }}/data
      ignore_errors: yes
      when: recovery_conf.stat.isreg is defined

    - name: ensure replica is not in recovery mode
      command: psql -U postgres -t -c "select pg_is_in_recovery();"
      register: recovery_mode
      changed_when: false
      become_user: postgres

    - name: check that recovery mode is off
      debug:
        msg: "Recovery mode is '{{ recovery_mode.stdout.strip() }}'"
      failed_when: recovery_mode.stdout.strip() != 'f'
