---

- hosts: all
  gather_facts: no
  become: true
  vars:
    pkgs_to_remove:
    - ansible-tower*
    - rabbitmq-server*
    - '*postgresql*'
    dep_pkgs_to_remove:
    - ansible
    - python2-jmespath
    - apr
    - apr-util
    - bubblewrap
    - erlang
    - gd
    - git
    - gperftools-libs
    - libXpm
    - libgnome-keyring
    - libsemanage-python
    - libunwind
    - memcached
    - mercurial
    - neon
    - nginx*
    - pakchois
    - perl-Error
    - perl-Git
    - perl-TermReadKey
    # postgresql96 and libs should be covered by pkgs_to_remove
    #- postgresql96
    #- postgresql96-libs
    - python-devel
    - python-meld3
    - python-virtualenv
    - rabbitmq-server
    - socat
    - subversion
    - subversion-libs
    - supervisor
    - python-psycopg2
    - setools-libs
    files_to_remove:
    - /etc/tower
    - /var/log/tower
    - /etc/yum.repos.d/ansible-tower.repo
    parent_dirs_to_remove:
    - /var/lib/pgsql
    - /var/lib/awx
    - /var/lib/rabbitmq
  tasks:
  - name: ensure tower services are stopped
    command: ansible-tower-service stop
    ignore_errors: yes

  - name: remove packages
    yum:
      name: "{{ pkgs_to_remove }}"
      state: absent

  - name: remove dep packages
    yum:
      name: "{{ dep_pkgs_to_remove }}"
      state: absent
    when: uninstall_deps | default(false)

  - name: get awx dir list
    find:
      paths: "{{ parent_dirs_to_remove }}"
      recurse: no
      file_type: any
    register: awx_paths

  - name: set awx file list
    set_fact:
      awx_file_list: awx_paths.files | json_query('[*].path')

  - name: cleanup files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ files_to_remove }}"
      - "{{ awx_file_list }}"

  # handles case where top-level dir is a mountpoint
  - name: cleanup parent directories
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ parent_dirs_to_remove }}"
    ignore_errors: yes

  - name: clean yum cache
    command: "{{ item }}"
    with_items:
    - "yum clean all"
    - "rm -rf /var/cache/yum"


# Review Support article for more information https://access.redhat.com/solutions/3107181
