- name: Start firewalld if it is enabled and not running
  service:
    name: firewalld
    state: started
  when:
    - systemctl_unit_files.stdout_lines | select('match','firewalld.service\s+enabled') | list | length == 1
    - firewalld_running.rc != 0

- name: Enable base Tower firewall ports
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    immediate: yes
    zone: "{{ tower_firewalld_zone }}"
  when: inventory_hostname in groups['tower']
  with_items: "{{ tower_firewall_ports }}"

- name: Enable HA Tower firewall ports
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    immediate: yes
    zone: "{{ tower_firewalld_zone }}"
  when: inventory_hostname in groups['tower'] and groups['tower']|length > 1
  with_items: "{{ tower_firewall_ha_ports }}"

- name: Enable HA Tower firewall management ports
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    immediate: yes
    zone: "{{ tower_firewalld_zone }}"
  when: inventory_hostname in groups['tower'] and groups['tower']|length > 1 and firewalld_rabbitmq_enable_manager|bool
  with_items: "{{ tower_cluster_management_ports }}"

- name: Enable Standalone Database firewall ports
  firewalld:
    port: '{{item}}/tcp'
    permanent: true
    state: enabled
    immediate: yes
    zone: "{{ tower_firewalld_zone }}"
  when: groups['database'] is defined and inventory_hostname in groups['database']
  with_items: "{{ database_firewall_ports }}"
